### PR TITLE
aarch32 build

### PR DESCRIPTION
**Pull request by tristeng**
Hey @Spasi 

Creating this pull request for a new master-aarch32 branch - I've commented out the uploading stuff so I could ensure the build passes on travis first. How should I proceed? Will you make a master-aarch32 branch first? Should I uncomment out the upload commands in the travis file? Or is this something you will do?

I decided to use a more up-to-date GCC compiler from linaro - they also provide a proper aarch64 compiler and I've also created a branch for that, but I intend to get aarch32 working first (for all of LWJGL). Let me know how to proceed.

Tristen

### CODE REVIEW

**Comment by Spasi** [comment]
Hey @tristeng,

This is looking good, but I won't have time to work with it for a few more days (going through a huge release at work). A few quick comments:

- Yes, ignore the S3 commands, I'll sort them out when the PR is merged.
- I'll probably use `master-arm32` as the branch name. You don't have to change anything now.
- It's not a big deal, but could you please move the `arm.toolchain.cmake` variables in `travis.yml`? Use either separate `export` commands or inline before the first `cmake command (it should work either way). It will be easier to maintain in the future if all information is in a single file.
- I'm not familiar with ARM toolchains. Is there a particular reason you chose the Linaro toolchain? Are there other options we could consider? What are the pros and cons of each one? Will there be compatibility issues we'll have to worry about?

**Comment by tristeng** [comment]
No rush, I'll be away until next week anyway. Sure, I can move the variables out and ditch the toolchain file. I went with linaro since they have frequent updates and support much newer gnu compiler versions (7.3) - I was afraid that relying on a dormant Raspberry Pi toolchain (gcc 4.9) project would mean we might be restricting the project to older architectures or even only architectures supported by the pi. 4.9 seems too far out of date, especially since I think the raspian os ships with 6.x I think

**Comment by tristeng** [comment]
My weekend plans fell through, so I'm working on this now :) 

I've created a new branch [master-arm32](https://github.com/tristeng/dyncall/tree/master-arm32) and removed the toolchain file and used env vars instead. If you are happy with my somewhat light research on the ARM toolchain options, let me know and I can replace this pull request with another.

**Comment by Spasi** [comment]
You can go ahead with creating another PR, but I would like to continue the toolchain discussion. Every time I've tried bumping the GCC version (`4.8.4` currently), there had been issues with a small subset of users. The trouble is that static compilation is next to impossible on Linux, so any binaries we generate always have certain dependencies (glibc, etc). Going all the way to 7.3 will be problematic I think.

**Comment by tristeng** [comment]
Makes sense, happy to continue the discussion. Seems that Linaro only goes back to 4.9 (similar to the Raspberry Pi tools project). Might be fun to see if I can build a toolchain for 4.8.4 :)

Another piece to discuss (for the overall project of getting LWJGL building on ARM) is the `wrap_memcpy.c` files I've come across in in LWJGL and assimp (and I'm guessing in other dependent projects). The toolchains don't like the 
`__asm__(".symver old_memcpy,memcpy@GLIBC_2.2.5");` 
since I _think_ the toolchain doesn't have that version of GLIBC in its system root (it seems to only come with 2.24). Some of the suggestions to workaround this seem tricky from what I've [read](https://stackoverflow.com/questions/8823267/linking-against-older-symbol-version-in-a-so-file). I'm looking into building/importing glibc at 2.2.5 but I'm also testing the "replace memcpy with memmove" strategy but this seems risking since I don't know these libraries well.

Do you have any insight or suggestions here?

**Comment by Spasi** [comment]
The [memcpy saga](https://www.win.tue.nl/~aeb/linux/misc/gcc-semibug.html) is a major pita and not using the `.symver` workaround causes the kinds of issues I mentioned above, i.e. `dlopen` failing because of missing dependencies. Notably, CentOS came with an old glibc version (< 2.14, until recently at least) and it's a non-trivial process to upgrade to a newer version.

GLIBC uses symbol versioning and maintains backwards compatibility when functions are upgraded. So, the workaround should work fine on 2.24 for example, `memcpy@GLIBC_2.2.5` will be available.

**Pull request closed without merging**
